### ISSUE TITLE
Holos error

### ISSUE THREAD

**Issue by 1luciasanguinetti** [holos-aafc/Holos#123]
### Contact Details

lucia.sanguinetti1@ucalgary.ca

### Expected Behaviour

I uninstalled and installed Holos again, but the same issue happened. It's the latest version. Once I enter a farm I have saved, it gets stuck after some moments. 

### Actual Behaviour

.

### Describe the Issue & Steps to Reproduce

.

### Error Message

An unexpected error occurred in the application. Data has been saved. To help troubleshoot this error, create a new issue in Holo's official github repository https://github.com/holos-aafc/Holos/issues . Before create a new issue, click the ‘Copy to Clipboard’ button. This will copy relevant information about the error to your computer’s clipboard. You can then paste this information in the "Error Message" field of the Bug/Issue report. Including this information in your issue report can help us troubleshoot and resolve this error.

Object reference not set to an instance of an object.

Polygon: 798008
Province: Alberta
____________________________________________________
System.NullReferenceException

Message:
Object reference not set to an instance of an object.

Stack Trace:
   at H.Core.Services.LandManagement.FieldResultsService.CalculateUpstreamEnergyEmissionsFromFertilizer(CropViewItem viewItem, Farm farm)
   at H.Core.Services.LandManagement.FieldResultsService.CalculateCropEnergyResults(CropViewItem viewItem, Farm farm)
   at H.Core.Services.LandManagement.FieldResultsService.CalculateFinalResultsForField(List`1 viewItemsForField, Farm farm, Guid fieldSystemGuid)
   at H.Core.Services.LandManagement.FieldResultsService.CalculateFinalResults(Farm farm)
   at H.Core.Services.FarmResultsService.CalculateFieldResults(Farm farm)
   at H.Core.Services.FarmResultsService.CalculateFarmEmissionResults(Farm farm)
   at H.Views.SupportingViews.OpenFarm.OpenFarmViewModel.SetInitialResultsState()
   at H.Views.SupportingViews.OpenFarm.OpenFarmViewModel.OnOpen(Object o)
   at Prism.Commands.DelegateCommand`1.Execute(T parameter)
   at Prism.Commands.DelegateCommand`1.Execute(Object parameter)
   at Prism.Commands.DelegateCommandBase.System.Windows.Input.ICommand.Execute(Object parameter)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at Telerik.Windows.Controls.RadButton.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

TargetSite:
Double CalculateUpstreamEnergyEmissionsFromFertilizer(H.Core.Models.LandManagement.Fields.CropViewItem, H.Core.Models.Farm)

Source:
H.Core

HResult:
-2147467261

### Holos Version Number

4.0.0.336

### Code of Conduct

- [X] I agree to follow Holos' Code of Conduct.

**Comment by holos-aafc** [comment]
Does this farm have any fertilizer applications for any of the fields? If so, can you list the blend types (the options selected from the drop down menu on the fertilizer tab) that you are using with this farm?
