### ISSUE TITLE
Holos crashes systematically when trying to edit a historical or projected practice in the Timeline view

### ISSUE THREAD

**Issue by gfortinLogiag** [holos-aafc/Holos#34]
### Contact Details

guillaume.fortin@logiag.com

### Expected Behaviour

I have worked with the same farm for the last week and have been able to modify the projected practice to test various scenarios. I was expecting this feature to still work in the same way.

### Actual Behaviour

When starting Holos today, it downloaded a new version which crashes whenever I try to edit a projected or historical practice. The behavior seems to occur for this farm only. I am able to edit the historical or projected practice for another farm.

### Describe the Issue & Steps to Reproduce

1. Open a specific farm (or import it from json file)
2. Go to timeline view
3. Click on Edit Selected 
4. Holos crashes completely

### Error Message

An unexpected error occurred in the application. Data has been saved. To help troubleshoot this error, create a new issue in Holo's official github repository https://github.com/holos-aafc/Holos/issues . Before create a new issue, click the ‘Copy to Clipboard’ button. This will copy relevant information about the error to your computer’s clipboard. You can then paste this information in the "Error Message" field of the Bug/Issue report. Including this information in your issue report can help us troubleshoot and resolve this error.

Object reference not set to an instance of an object.

Polygon: 541047
Province: Quebec
____________________________________________________
System.NullReferenceException

Message:
Object reference not set to an instance of an object.

Stack Trace:
   at H.Views.ComponentViews.LandManagement.FieldSystem.ViewModel.FieldSystemViewModel.InitializeSoil()
   at H.Views.ComponentViews.LandManagement.FieldSystem.ViewModel.FieldSystemViewModel.InitializeViewModel(FieldSystemComponent component)
   at H.Views.TimelineViews.LandManagement.CroppingSystem.FieldSystemTimelineViewModel.EditComponent(ComponentBase component)
   at H.Views.TimelineViews.LandManagement.CroppingSystem.FieldSystemTimelineViewModel.OnEditComponent(Object o)
   at Prism.Commands.DelegateCommand`1.Execute(T parameter)
   at Prism.Commands.DelegateCommand`1.Execute(Object parameter)
   at Prism.Commands.DelegateCommandBase.System.Windows.Input.ICommand.Execute(Object parameter)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at Telerik.Windows.Controls.RadButton.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

TargetSite:
Void InitializeSoil()

Source:
H

HResult:
-2147467261

### Holos Version Number

4.0.0.459

### Code of Conduct

- [X] I agree to follow Holos' Code of Conduct.

**Comment by holos-aafc** [comment]
Added check for field-level soil type in view model.

**Comment by holos-aafc** [comment]
4.0.0.460 is ready for download. @gfortinLogiag can you verify this fixes the issue for you before I close this bug?

**Comment by gfortinLogiag** [comment]
The issue is fixed! Thanks!

**Comment by holos-aafc** [comment]
Closed
